### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by varlesh** [drauger-os-development/drauger-welcome#10]
Hi Drauger devs. You use Papirus on your system... i like it.
But why you offend my mom?
And why i can't access on your site?
![Screenshot_20210812_162523](https://user-images.githubusercontent.com/8083855/129196274-b9bbba18-43aa-4f78-8595-3288743c48bc.png)

**Comment by xiaoyong-wang** [comment]
Your IP Range or Country was probably blocked. I recommend asking in the community Discord Server or Telegram Group Chat.

**Comment by varlesh** [comment]
I know about blocking. These insults are inappropriate

**Comment by xiaoyong-wang** [comment]
> I know about blocking. These insults are inappropriate

It's a joke.

**Comment by Batcastle** [comment]
I apologize for the return text. This page, under normal conditions, should never been seen by humans. It's part of our anti-bot system. I recommend trying turning down your privacy settings in your browser. Our site relies on things such as Javascript in order to function properly. 

If you continue having issues with this, please join our [Discord server](https://discord.gg/JW8FGrc) or [Telegram group.](https://t.me/draugeros), and let us know. Our community would be more than happy to help you out.

Otherwise, I am closing this issue as this is unrelated to the package this repository is for.
